# Generated by Django 5.1.3 on 2024-12-06 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='sobrenome',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
